---
version: 2
plan:
  project-key: WEBCO
  key: VLUI
  name: webcomponenten-vl-ui

triggers:
  - polling: 130

variables:
  release_version: patch

stages:
  - Build:
      jobs:
        - Build
  - Release:
      manual: true
      jobs:
        - Release

Build:
  key: BD

Release:
  key: REL
  tasks:
    - clean
    - script: |
        #!/usr/env/bin bash
        set -e
        /opt/scripts/git/git-repository-information-restore.sh
        export git_repo="${bamboo_repository_git_repositoryUrl}"
        export release_version="${bamboo.release_version}"
        docker-compose -f docker-compose-release.yml run release
      interpreter: /bin/sh
  final-tasks:
    - script: /opt/scripts/docker/stop-docker-containers.sh
  requirements:
    - REMOTE_ONLY

---
version: 2
plan:
  key: WEBCO-VLUI

plan-permissions:
  - groups:
      - bamboo-admin
      - bamboo-release
      - developer-admin
    permissions:
      - view
      - edit
      - build
      - clone
      - admin
